### ISSUE TITLE
Deprecated post match

### ISSUE THREAD

**Issue by cwchristerw** [Mikaela/mikaela.github.io#117]
RUNNING LOCALLY DOES REVEAL THIS KIND OF MESSAGE FOR ALL POSTS
`Deprecation: A call to '{% post_url 2015-05-29-graduation %}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.`

**Comment by cwchristerw** [comment]
HOW TO REPEAT THIS TO GET THE MESSAGE
Install to local machine using docker or local installation, get instructions for that in #116

**Comment by Mikaela** [comment]
I have faint idea of GitHub running too old version that doesn't support that format, but I am not entirely sure and that was a very long time ago, so hopefully the situation has changed since then.

**Comment by Mikaela** [comment]
OK, so it wants me to add the directory in front of it. As everything is in `blog/_posts` and `_posts` disappears in the URL, the warning you quoted is fixed by:

```diff
-[I graduated on 2015-05-29.]({% post_url 2015-05-29-graduation %})*
+[I graduated on 2015-05-29.]({% post_url blog/2015-05-29-graduation %})*
```

I guess this isn't so painful to fix, I will change a few and then push and if GitHub doesn't complain, I will keep on pushing.

**Comment by Mikaela** [comment]
Judging by https://github.com/Mikaela/mikaela.github.io/deployments I am correct and can fix this. I should also really fix Travis.
