### ISSUE TITLE
Matrix community abuse management - Conduit git has ACL support

### ISSUE THREAD

**Issue by Mikaela** [Mikaela/mikaela.github.io#274]
https://gitlab.com/famedly/conduit/-/issues/67#note_8986227d70294975d69c974e9c07d85a7f12c48c should be noted by strikethroughing it sooner or later, possibly preferably once they have a tag containing it? [Then again GitLab itself isn't my friend regarding that.](https://gitlab.com/gitlab-org/gitlab/-/issues/27546)

**Comment by timokoesters** [comment]
Conduit v0.3.0 was recently released and has acl support

**Comment by Mikaela** [comment]
Sorry, I forgot to close this in https://github.com/Mikaela/mikaela.github.io/commit/56adc8acb32037e7c6b3195fae402b5bf092147e
