### ISSUE TITLE
Blog idea: Am I allowed to exist in public sports spaces too? Post-transitioning#2, (Type this in Finnish.)

### ISSUE THREAD

**Issue by Mikaela** [Mikaela/mikaela.github.io#344]
A recent newspaper article recently accused unisex bathrooms and changing/dressing rooms of making people feel insecure.

- https://www.hs.fi/kotimaa/art-2000010056051.html 

In reality unisex spaces make gender non-comforming people safer, whether they are closeted, non-binary uncomfortable with going to either binary segregated space, or like me unwilling to risk either hate or ignorance.

This blog idea also bridges to my current situation with transitioning and serves to update the previous post.

- https://aminda.eu/blog/english/2017/04/30/post-trans.html

During the pandemic I started thinking of whether to actually proceed to vulvoplasty, got to the surgery queue, received seven (7) A4 pages of the surgery, preparation and risks. Based on this I decided that I am not willing to accept the risks for imperfect surgery that destroys healthy tissue just for other people and instead I am going to be visibly trans and get a ⚧️ tattoo instead as a less risky option.

This circles back to the question, where can I go? As I refuse to change my body for other people, I imagine I cannot go to women's changing/dressing rooms due to having a penis risking shocking someone and I certainly cannot go to men's spaces due to not being a man, having brasts and not having a penis.

This blog post, which I seem to have mostly written in this idea, would also be a great place to come out as genderdoe, which English speakers may have figured out from my pronouns already.

**Comment by Mikaela** [comment]
Käyttöoikeusmerkki exists and allows wearing swimsuit in saunas at swimming halls. However the tattoo might kind of reveal that the other common causes for wearing it may not apply in this case.

**Comment by Mikaela** [comment]
Then again I want to criticise some writings about _käyttöoikeusmerkki_ since some of them imply that transitioning ends to gender reaffirming surgery, which I am not going to have and which I doubt would be that gender reaffirming for me.

I am going to affirm myself by not letting the society dictate my body and being a visible reminder that there are other "genders" than "male", "female" and "transitioning".

**Comment by Mikaela** [comment]
Another issue are places who claim to welcome everyone and advertise friendliness to gender diversity, but yet fail to consider the dressing/changing rooms.

I had this issue early 2023 when looking at options for rehabitative employment and in addition to trans-friendliness I was introduced to a gym. However they hadn't considered the changing/dressing rooms at all and I was the first one to ask about that.

**Comment by Mikaela** [comment]
Should I be providing solutions? Do I know solutions myself? 

I think having unisex areas (not necessarily replacing segregated ones) is a step in the right direction as no one should be told they don't belong to unisex spaces.

Is it possible to build third saunas to swimming halls or third dressing room when everything is build with segregation to two in mind?

Is this where I ask the reader to tell me what is their solution in perfect world?

**Comment by EchedeyLR** [comment]
I strongly believe unisex areas should replace segregated ones. If not radically, at least they should replace it with time and the help of better-educated people.

**Comment by Mikaela** [comment]
The linked article comments included someone saying cis girls feel better with periods in gendered spaces due to having trash cans, which the solution should include for people who experience periods. Ref: https://yle.fi/a/74-20063566?origin=rss

Many people have also brought up women's spaces generally being cleaner than mens. I wonder how to fit it in the equation here.

The article is focusing on bathrooms (which I don't have an issue with due to "passing" as a woman when clothed and those tend to have stalls) while also mentoning changing spaces where I have the issue with, just like saunas/showers/swimming halls.

**Comment by Mikaela** [comment]
> There are more or less valid reasons for segregation such as religion and people of both genders having traumas with "the other set of genitalia", while forgetting that men are able of raping men and women are capable of raping women and women are capable of raping men and men are capable of raping women and what I keep repeating in other contexts that people don't want to acknowledge that everyone they represent isn't perfect or that other minorities are also capable of bad as well as good.

This feels like a long blog post and long work to reassemble these individual notes into something coherent.

**Comment by EchedeyLR** [comment]
Why not a blog post representing an inner discussion about the topic, the different paths, etc and how you consider them?

**Comment by Mikaela** [comment]
> Why not a blog post representing an inner discussion about the topic,

It's not my style, but if I felt like it sometime, I think the notes such as this issue, will provide source material for that if I change my mind in the future.

> the different paths, etc. and how you consider them?

Is this about the same subject or transitioning in general? I don't think I have anything to add to that discussion, other than what you can already see at https://aminda.eu/blog or this issue.

**Comment by EchedeyLR** [comment]
>  Is this about the same subject or transitioning in general? I don't think I have anything to add to that discussion, other than what you can already see at https://aminda.eu/blog or this issue.

I am unsure, I thought that more could be added or even comparing the situations. Yes, most of it is already written here.

**Comment by Mikaela** [comment]
Loosely related: https://yle.fi/a/74-20065589

**Comment by Mikaela** [comment]
I have took a tattoo and decided that my existence is not my problem.
