### ISSUE TITLE
Index doesn't pass HTML validator

### ISSUE THREAD

**Issue by Mikaela** [Mikaela/mikaela.github.io#71]
* https://validator.w3.org/nu/?doc=https%3A%2F%2Fmikaela.info%2F

Upgrade Insecure Requests can be ignored as I know it's valid, other things need fixing.

**Comment by Mikaela** [comment]
Requires learning Sass.

* http://sass-lang.com/

> Sass stands with trans detainees. [Donate to the Trans Justice Funding Project.](https://www.tfaforms.com/369883)

not bad thing to learn.

**Comment by Mikaela** [comment]
3 isn't real error, 4 I have no idea where that issue is.

**Comment by lamperi** [comment]
You cannot nest paragraphs. Starting another p-tag will implicitly end the previous one. See line 97 which starts with two p tags.

**Comment by Mikaela** [comment]
Thanks :)

Now the only complaint is `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">` which I wonder as it's supported by Chrome & co and is supposed to be w3's own standard.

**Comment by Mikaela** [comment]
Confirmed on #whatwg, the validator just hasn't been upgraded to understand that yet.

* https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-content-security-policy
