### ISSUE TITLE
Gajim on Windows 10 on Zaldaryn

### ISSUE THREAD

**Issue by Mikaela** [Mikaela/mikaela.github.io#87]
* Joindiaspora.com: 16108077 0CF235EA 626955E8 F651E534 A7AC4B98 822879F8 9BFD6685 CA1DCF3A
* Kapsi.fi: 7459B635 5822ABEF DA13120D 3C670691 431D35AB 28C8E69F 952395E1 CD036C43

**Comment by jagnyx** [comment]
Can confirm.

**Comment by Mikaela** [comment]
Windows/sedric:

* Joindiaspora.com: 92A42B79 60475A6E 8E5489FE 3B593A39 42F4756E CF4B852C F5C348C8 23F67972
* Kapsi.fi: 9792DD09 4D553A08 32E1C277 4504FC84 283391F9 5E6A98AA 03135AC3 01A8CD23

**Comment by Mikaela** [comment]
@jagnyx Would you happen to remember seeing `joindiaspora.com: 43EDCC68 E9753D43 258EDEE0 274A0057 67BD5DEE 5FF503D2 A798FE77 97A37C64` from me?

It appears on Gajim on Sedric_W10, but I have no idea what it is and neither Conversations has seen it.

I guess it might be leftover from the old keys I accidentally marked as entirely not trusted and removed to regenerate those you see from my previous comment.
