### ISSUE TITLE
Minor flaw in article about SASL in weechat

### ISSUE THREAD

**Issue by Vaesper** [Mikaela/mikaela.github.io#91]
I promised to explain my point more clearly in this platform, so here it is. You state

> PLAIN is simple “login using username and password” mechanism that sends the username and password in plaintext which isn’t an issue if you also use SSL like you should.

I think the "isn't an issue" part here is a slight misrepresentation, as sending plain PW does have its downsides even if over a secure, authenticated TLS channel. The point is that you don't want to trust the server with the plain password. This is the reason you don't store pw's in plaintext in databases, but in some hashed form.

Now, I am not familiar enough with IRC auth to state exactly which scheme does "do it right", and it is certainly a field of knowledge with many pitfalls that requires thorough analysis to be trusted, all I want to say is that "plain over TLS", while I agree better than the DH auth options, is not perfect. TLS is not a magic potion, and exposing your plain pw to the server is still not a good idea.

**Comment by Mikaela** [comment]
As I didn't see your answer at IRC and I encountered this issue again while checking email, are you satisfied with the fix @Vaesper ?

**Comment by Vaesper** [comment]
Eh, if you trust the server you don't need to use different password everywhere, but you shouldn't trust the server anyway so I think it is fine. I still think that it would be better to have a scheme where the IRC server itself never sees the plaintext pw since then there is less risk for users who use the same pw elsewhere, but since the DH auth schemes also expose the plaintext pw to the services, "plain over TLS" is still a clear improvement without any disadvantages (compared to the DH alternatives).

**Comment by Mikaela** [comment]
There are also SASL EXTERNAL, EDSCA256-CHALLENGEAUTH (cobsidered bad) and SCRAM-something, but they aren't simple and most of basic users aren't going to setup them even if I wrote instructions that are better documented elsewhere and can be quite OS-specific.
