### ISSUE TITLE
Typo necressary → necessary

### ISSUE THREAD

**Issue by tuxayo** [Mikaela/mikaela.github.io#98]
https://github.com/Mikaela/mikaela.github.io/blob/master/pages/about.markdown#ace--relationship-anarchist

> However labels such as partner still appear to be necressary with unique relationships based on their development or otherwise I am not understood.

I'm not a native speaker but it seem very likely a typo.

Very interesting read BTW, thanks for sharing this :)

**Comment by Mikaela** [comment]
Thanks for noticing it and sorry for very slow reacting, I had somehow forgotten this entirely. I will try to fix this as soon as I boot something with git and gpg set up.
